version: "3.2"
services:
  nodejs:
    build:
        context: ./backend
        dockerfile: dockerfile 
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASS=moepass
      - MYSQL_DB=x_database
    ports:
      - "30001:8005"
    container_name: moe-nodejs-app
  
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass 
      - MYSQL_DATABASE=x_database
    container_name: moe-mysql-app
    volumes:
      - "./db-lib:/var/lib/mysql"
      - ./db-init:/docker-entrypoint-initdb.d:ro
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT= 3306
    container_name: moe-phpmyadmin-app

  frontend:
    build:
      context: ./frontend/X_clone
      dockerfile: Dockerfile
    ports:
      - "30003:8080"
    volumes:
      - ./frontend/X_clone:/frontend/X_clone
    depends_on:
      - nodejs
    container_name: moe-frontend-app
