version: '3.1'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_base_de_donnees
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_mot_de_passe
    volumes:
      - "./db-lib:/var/lib/mysql"
      - "./mysql-init:/docker-entrypoint-initdb.d"
    restart: always
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8095:80"
    environment:
      PMA_HOST: database
      PMA_USER: mon_user
      PMA_PASSWORD: mon_mot_de_passe
      PMA_ARBITRARY: 1
    restart: always